[build]
target = "x86_64-unknown-none.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner --quiet"

[unstable]
panic-abort-tests = true
build-std-features = ["compiler-builtins-mem"]
build-std = ["alloc", "core", "compiler_builtins"]
